[project]
name = 'blockchain-community-governance-platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.community-proposal-system]
path = 'contracts/community-proposal-system.clar'
clarity_version = 2
epoch = 2.5

[contracts.democratic-voting-engine]
path = 'contracts/democratic-voting-engine.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
